version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: department_db
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring_app_container
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/department_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
    ports:
      - "8080:8002"

volumes:
  mysql_data: